# Site settings
author: Olivia Kesler 
title: The Little Engine That Codes
header-img: img/home-bg.png
email: oakesler@protonmail.ch
copyright_name: Olivia Kesler 
description: > # this means to ignore newlines until "baseurl:"
  i think i code, i think i code, i think i code....
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  oakesler

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
